import org.json.*;
import converter.*;
import data.*;
import modules.*;

/*
 * ATTENTION: DO NOT EDIT THIS FILE UNLESS YOU ARE A PROGRAM DEV LEADER
 *            Please Edit the TestDriver class for your own personal use.
 * If everyone edits this file, many conflicts will need to be resolved.
 * Rewrite or copy this class to a new TestDriver class (TestDriver.java) and do not commit those changes
 */
public class BaseballReporter 
{
    public static void main(String[] args) throws Exception
    {
        // Determine file path: either default or from args
        String filePath = "data/data.json";
        if(args.length != 0 && args[0].length() > 0)
            filePath = args[0];
        System.out.println("Reading from "+filePath);
        
        // conversion //
        JSONConverter conv = new JSONConverter(filePath);
        JSONObject objectifiedData = conv.getData();
        System.out.println(conv.toString());
        
        // data preparation //
        ReportData finalData = new ReportData(objectifiedData);
        
        // modules creation and output //
        Modules modules = new Modules(finalData);
        String output = modules.generate();
        System.out.println(output);
    }
}
