//import java.io.FileReader;

//our libs
import reporter.*;
import modules.*;
import converter.*;

/*
 * ATTENTION: DO NOT EDIT THIS FILE UNLESS YOU ARE A PROGRAM DEV LEADER
 *            Please Edit the TestDriver class for your own personal use.
 * If everyone edits this file, many conflicts will need to be resolved.
 * Rewrite or copy this class to a new Test class (Test.java) and do not commit those changes
 */
public class Program 
{
	public static void main(String[] args)
	{
		// Determine file path: either default or from args
		String filePath = "data/data.csv";
		if(args.length != 0 && args[0].length() > 0)
			filePath = args[0];
			
		Converter convert = new CSVConverter(filepath);
		ReportData data = convert.getData();
		// Alternative: ReportData data = (new Converter(filePath)).convertReportData();
		
		String output = "";
		Module[] modules = { //TODO: add modules
		                    
		                   };
		for(int i = 0; i < modules.length; i++) {
			output += modules[i].generate() + "\n";
		}
		
		System.out.println(output);
		return;
	}
}
