//import java.io.FileReader;

//our libs
import reporter.*;
import modules.*;
import converter.*;
import org.json.*;

/*
 * ATTENTION: DO NOT EDIT THIS FILE UNLESS YOU ARE A PROGRAM DEV LEADER
 *            Please Edit the TestDriver class for your own personal use.
 * If everyone edits this file, many conflicts will need to be resolved.
 * Rewrite or copy this class to a new TestDriver class (TestDriver.java) and do not commit those changes
 */
public class Program 
{
    public static void main(String[] args)
    {
        System.out.println("hello world");
        // Determine file path: either default or from args
        String filePath = "data/data.json";
        if(args.length != 0 && args[0].length() > 0)
            filePath = args[0];
        System.out.println("Reading from "+filePath);
        
        JSONObject data;
        try{
            JSONConverter conv = new JSONConverter(filePath);
            data = conv.getData();
            System.out.println(conv.toString());
        } catch (Exception e){
            e.printStackTrace();
        }
        
        String output = "";
        // TODO: Create modules and concatenate to output
        // output += (new ReportModule(data)).generate();
        // TODO: Should we just pass modules the JSONObject data object?
        
        System.out.println(output);
    }
}
