import java.io.FileReader;
import reporter.*;

/*
 * ATTENTION: DO NOT EDIT THIS FILE UNLESS MAKING GLOBAL CHANGES
 * If everyone edits this file, many conflicts will need to be resolved.
 * Rewrite or copy this class to a new Test class (Test.java) and do not commit those changes
 */
public class Program 
{
	public static void main(String[] args)
	{
		// Determine file path: either default or from args
		String filePath = "data/data.csv";
		if(args.length != 0 && args[0].length() > 0)
			filePath = args[0];
			
		// TODO: Convert file to ReportData using Converter child
		// ReportData data = (new Converter(filePath)).convertReportData();
		
		String output = "";
		// TODO: Create modules and concatenate to output
		// output += (new ReportModule(data)).generate();
		
		System.out.println(output);
	}
}
